parameters:
  nb_servers: 3

server1:
  ip: 140.77.180.89
  port_server: 16842
  port_client: 25984

server2:
  ip: 140.77.180.89
  port_server: 12347
  port_client: 12348

server3:
  ip: 140.77.180.89
  port_server: 12349
  port_client: 12340
